version: "3.4"

services:
  bbl.back-end:
    image: bbl:backend-0.1.0
    container_name: BBLapi
    ports:
      - "8071:80"
      - "6443:443"
    build:
      context: .
      dockerfile: BBL.API/Dockerfile
    # depends_on:
    #   - mssql.server

  # mssql.server:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: Database
  #   ports:
  #     - 8002:1433
  #   environment:
  #     SA_PASSWORD: mlT0933z*
  #     ACCEPT_EULA: Y
