using System.Data;
using System.Xml.Linq;
using BBL.Core.Constants;
using BBL.Core.Enums;
using BBL.Entities.Concrete;
using BBL.Entities.Identity;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace BBL.DataAccess.EntityFramework.Context;

public static class DataMonitoringDbInitialiserExtensions
{
    public static async Task InitialiseDatabaseAsync(this WebApplication app)
    {
        using IServiceScope? scope = app.Services.CreateScope();

        BBLDbContextInitialiser? initialiser =
            scope.ServiceProvider.GetRequiredService<BBLDbContextInitialiser>();

        await initialiser.InitialiseAsync();

        await initialiser.SeedAsync();
    }
}

public class BBLDbContextInitialiser
{
    private readonly ILogger<BBLContext> _logger;
    private readonly BBLContext _context;

    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;


    public BBLDbContextInitialiser(BBLContext context,
                                              ILogger<BBLContext> logger,
                                              UserManager<ApplicationUser> userManager,
                                              RoleManager<ApplicationRole> roleManager)
    {
        _context = context;
        _logger = logger;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public async Task InitialiseAsync()
    {
        try
        {
            if (_context != null)
            {
                await _context.Database.MigrateAsync();
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "An error occurred while initialising the database.");
            throw;
        }
    }

    public async Task SeedAsync()
    {
        try
        {
            await TrySeedAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "An error occurred while seeding the database.");
            throw;
        }
    }

    public async Task TrySeedAsync()
    {
        #region Cities

        if (!_context.Cities.Any())
        {
            var industries = new List<City>
        {
            new City{CityName="Adana"},
            new City{CityName="Adıyaman"},
            new City{CityName="Afyon"},
            new City{CityName="Ağrı"},
            new City{CityName="Amasya"},
            new City{CityName="Ankara"},
            new City{CityName="Antalya"},
            new City{CityName="Artvin"},
            new City{CityName="Aydın"},
            new City{CityName="Balıkesir"},
            new City{CityName="Bilecik"},
            new City{CityName="Bingöl"},
            new City{CityName="Bitlis"},
            new City{CityName="Bolu"},
            new City{CityName="Burdur"},
            new City{CityName="Bursa"},
            new City{CityName="Çanakkale"},
            new City{CityName="Çankırı"},
            new City{CityName="Çorum"},
            new City{CityName="Denizli"},
            new City{CityName="Diyarbakır"},
            new City{CityName="Edirne"},
            new City{CityName="Elazığ"},
            new City{CityName="Erzincan"},
            new City{CityName="Erzurum"},
            new City{CityName="Eskişehir"},
            new City{CityName="Gaziantep"},
            new City{CityName="Giresun"},
            new City{CityName="Gümüşhane"},
            new City{CityName="Hakkari"},
            new City{CityName="Hatay"},
            new City{CityName="Isparta"},
            new City{CityName="Mersin"},
            new City{CityName="İstanbul"},
            new City{CityName="İzmir"},
            new City{CityName="Kars"},
            new City{CityName="Kastamonu"},
            new City{CityName="Kayseri"},
            new City{CityName="Kırklareli"},
            new City{CityName="Kırşehir"},
            new City{CityName="Kocaeli"},
            new City{CityName="Konya"},
            new City{CityName="Kütahya"},
            new City{CityName="Malatya"},
            new City{CityName="Manisa"},
            new City{CityName="Kahramanmaraş"},
            new City{CityName="Mardin"},
            new City{CityName="Muğla"},
            new City{CityName="Muş"},
            new City{CityName="Nevşehir"},
            new City{CityName="Niğde"},
            new City{CityName="Ordu"},
            new City{CityName="Rize"},
            new City{CityName="Sakarya"},
            new City{CityName="Samsun"},
            new City{CityName="Siirt"},
            new City{CityName="Sinop"},
            new City{CityName="Sivas"},
            new City{CityName="Tekirdağ"},
            new City{CityName="Tokat"},
            new City{CityName="Trabzon"},
            new City{CityName="Tunceli"},
            new City{CityName="Şanlıurfa"},
            new City{CityName="Uşak"},
            new City{CityName="Van" },
            new City{CityName="Yozgat"},
            new City{CityName="Zonguldak"},
            new City{CityName="Aksaray"},
            new City{CityName="Bayburt"},
            new City{CityName="Karaman"},
            new City{CityName="Kırıkkale"},
            new City{CityName="Batman"},
            new City{CityName="Şırnak"},
            new City{CityName="Bartın"},
            new City{CityName="Ardahan"},
            new City{CityName="Iğdır"},
            new City{CityName="Yalova"},
            new City{CityName="Karabük"},
            new City{CityName="Kilis"},
            new City{CityName="Osmaniye"},
            new City{CityName="Düzce"},
        };

            await _context.Cities.AddRangeAsync(industries);

            await _context.SaveChangesAsync();
        }

        #endregion

        #region Districts

        if (!_context.Districts.Any())
        {
            var districts = new List<District>
            {
                new District { CityId=34,DistrictName="Arnavutköy"},
                new District { CityId=34,DistrictName="Avcılar"},
                new District { CityId=34,DistrictName="Bağcılar"},
                new District { CityId=34,DistrictName="Bahçelievler"},
                new District { CityId=34,DistrictName="Bakırköy"},
                new District { CityId=34,DistrictName="Başakşehir"},
                new District { CityId=34,DistrictName="Bayrampaşa"},
                new District { CityId=34,DistrictName="Beşiktaş"},
                new District { CityId=34,DistrictName="Beylikdüzü"},
                new District { CityId=34,DistrictName="Beyoğlu"},
                new District { CityId=34,DistrictName="Büyükçekmece"},
                new District { CityId=34,DistrictName="Çatalca"},
                new District { CityId=34,DistrictName="Eminönü"},
                new District { CityId=34,DistrictName="Esenler"},
                new District { CityId=34,DistrictName="Esenyurt"},
                new District { CityId=34,DistrictName="Eyüp"},
                new District { CityId=34,DistrictName="Fatih"},
                new District { CityId=34,DistrictName="Gaziosmanpaşa"},
                new District { CityId=34,DistrictName="Güngören"},
                new District { CityId=34,DistrictName="Kağıthane"},
                new District { CityId=34,DistrictName="Küçükçekmece"},
                new District { CityId=34,DistrictName="Mimarsinan/Büyükçekmece"},
                new District { CityId=34,DistrictName="Sarıyer"},
                new District { CityId=34,DistrictName="Silivri"},
                new District { CityId=34,DistrictName="Sultangazi"},
                new District { CityId=34,DistrictName="Şişli"},
                new District { CityId=34,DistrictName="Zeytinburnu"},
                new District { CityId=34,DistrictName="Adalar"},
                new District { CityId=34,DistrictName="Ataşehir"},
                new District { CityId=34,DistrictName="Beykoz"},
                new District { CityId=34,DistrictName="Çekmeköy"},
                new District { CityId=34,DistrictName="Kadıköy"},
                new District { CityId=34,DistrictName="Kartal"},
                new District { CityId=34,DistrictName="Maltepe"},
                new District { CityId=34,DistrictName="Pendik"},
                new District { CityId=34,DistrictName="Sancaktepe"},
                new District { CityId=34,DistrictName="Sultanbeyli"},
                new District { CityId=34,DistrictName="Şile"},
                new District { CityId=34,DistrictName="Tuzla"},
                new District { CityId=34,DistrictName="Ümraniye"},
                new District { CityId=34,DistrictName="Üsküdar"},
                new District { CityId=6,DistrictName="100.Yıl"},
                new District { CityId=6,DistrictName="Akyurt"},
                new District { CityId=6,DistrictName="Altındağ"},
                new District { CityId=6,DistrictName="Aşağı Ayrancı"},
                new District { CityId=6,DistrictName="Ayaş"},
                new District { CityId=6,DistrictName="Bakanlıklar"},
                new District { CityId=6,DistrictName="Bala"},
                new District { CityId=6,DistrictName="Beşevler"},
                new District { CityId=6,DistrictName="Beypazarı"},
                new District { CityId=6,DistrictName="Beytepe"},
                new District { CityId=6,DistrictName="Çamlıdere"},
                new District { CityId=6,DistrictName="Çankaya"},
                new District { CityId=6,DistrictName="Çubuk"},
                new District { CityId=6,DistrictName="Elmadağ"},
                new District { CityId=6,DistrictName="Etimesgut"},
                new District { CityId=6,DistrictName="Evren"},
                new District { CityId=6,DistrictName="Gölbaşı"},
                new District { CityId=6,DistrictName="Güdül"},
                new District { CityId=6,DistrictName="Hasanoğlan"},
                new District { CityId=6,DistrictName="Haymana"},
                new District { CityId=6,DistrictName="Kahramankazan"},
                new District { CityId=6,DistrictName="Kalecik"},
                new District { CityId=6,DistrictName="Keçiören"},
                new District { CityId=6,DistrictName="Kızılcahamam"},
                new District { CityId=6,DistrictName="Macunköy"},
                new District { CityId=6,DistrictName="Mamak"},
                new District { CityId=6,DistrictName="Mehmet Akif Ersoy"},
                new District { CityId=6,DistrictName="Merkez"},
                new District { CityId=6,DistrictName="Nallıhan"},
                new District { CityId=6,DistrictName="Polatlı"},
                new District { CityId=6,DistrictName="Pursaklar"},
                new District { CityId=6,DistrictName="Sıhhıye"},
                new District { CityId=6,DistrictName="Sincan"},
                new District { CityId=6,DistrictName="Şaşmaz"},
                new District { CityId=6,DistrictName="Şereflikoçhisar"},
                new District { CityId=6,DistrictName="Yenimahalle"},
                new District { CityId=6,DistrictName="Yukarı Ayrancı"},
                new District { CityId=35,DistrictName="Aliağa"},
                new District { CityId=35,DistrictName="Altındağ"},
                new District { CityId=35,DistrictName="Balçova"},
                new District { CityId=35,DistrictName="Basmane"},
                new District { CityId=35,DistrictName="Bayındır"},
                new District { CityId=35,DistrictName="Bayraklı"},
                new District { CityId=35,DistrictName="Bergama"},
                new District { CityId=35,DistrictName="Beydağ"},
                new District { CityId=35,DistrictName="Bornova"},
                new District { CityId=35,DistrictName="Buca"},
                new District { CityId=35,DistrictName="Çankaya"},
                new District { CityId=35,DistrictName="Çeşme"},
                new District { CityId=35,DistrictName="Çınarlı"},
                new District { CityId=35,DistrictName="Çiğli"},
                new District { CityId=35,DistrictName="Dikili"},
                new District { CityId=35,DistrictName="Foça"},
                new District { CityId=35,DistrictName="Gaziemir"},
                new District { CityId=35,DistrictName="Güzelbahçe"},
                new District { CityId=35,DistrictName="Kapılar"},
                new District { CityId=35,DistrictName="Karabağlar"},
                new District { CityId=35,DistrictName="Karaburun"},
                new District { CityId=35,DistrictName="Karşıyaka"},
                new District { CityId=35,DistrictName="Kemalpaşa"},
                new District { CityId=35,DistrictName="Kemeraltı"},
                new District { CityId=35,DistrictName="Kınık"},
                new District { CityId=35,DistrictName="Kısıkköy"},
                new District { CityId=35,DistrictName="Kiraz"},
                new District { CityId=35,DistrictName="Konak"},
                new District { CityId=35,DistrictName="Kordon"},
                new District { CityId=35,DistrictName="Menderes(Cumaovası)"},
                new District { CityId=35,DistrictName="Menemen"},
                new District { CityId=35,DistrictName="Mersinli"},
                new District { CityId=35,DistrictName="Mezarlıkbaşı"},
                new District { CityId=35,DistrictName="Montrö"},
                new District { CityId=35,DistrictName="Narlıdere"},
                new District { CityId=35,DistrictName="Ödemiş"},
                new District { CityId=35,DistrictName="Pasaport"},
                new District { CityId=35,DistrictName="Seferihisar"},
                new District { CityId=35,DistrictName="Selçuk"},
                new District { CityId=35,DistrictName="Şirinyer"},
                new District { CityId=35,DistrictName="Tire"},
                new District { CityId=35,DistrictName="Torbalı"},
                new District { CityId=35,DistrictName="Urla"},
                new District { CityId=1,DistrictName="Aladağ"},
                new District { CityId=1,DistrictName="Ceyhan"},
                new District { CityId=1,DistrictName="Çukurova"},
                new District { CityId=1,DistrictName="Feke"},
                new District { CityId=1,DistrictName="İmamoğlu"},
                new District { CityId=1,DistrictName="Karaisalı"},
                new District { CityId=1,DistrictName="Karataş"},
                new District { CityId=1,DistrictName="Kozan"},
                new District { CityId=1,DistrictName="Merkez"},
                new District { CityId=1,DistrictName="Pozantı"},
                new District { CityId=1,DistrictName="Saimbeyli"},
                new District { CityId=1,DistrictName="Sarıçam"},
                new District { CityId=1,DistrictName="Seyhan"},
                new District { CityId=1,DistrictName="Tufanbeyli"},
                new District { CityId=1,DistrictName="Yumurtalık"},
                new District { CityId=1,DistrictName="Yüreğir"},
                new District { CityId=3,DistrictName="Basmakçı"},
                new District { CityId=3,DistrictName="Bayat"},
                new District { CityId=3,DistrictName="Bolvadin"},
                new District { CityId=3,DistrictName="Çay"},
                new District { CityId=3,DistrictName="Çobanlar"},
                new District { CityId=3,DistrictName="Dazkırı"},
                new District { CityId=3,DistrictName="Dinar"},
                new District { CityId=3,DistrictName="Döşemealtı"},
                new District { CityId=3,DistrictName="Emirdağ"},
                new District { CityId=3,DistrictName="Evciler"},
                new District { CityId=3,DistrictName="Hocalar"},
                new District { CityId=3,DistrictName="İhsaniye"},
                new District { CityId=3,DistrictName="İşcehisar"},
                new District { CityId=3,DistrictName="Kızılören"},
                new District { CityId=3,DistrictName="Merkez"},
                new District { CityId=3,DistrictName="Sandıklı"},
                new District { CityId=3,DistrictName="Sinanpaşa"},
                new District { CityId=3,DistrictName="Sincanlı"},
                new District { CityId=3,DistrictName="Sultandağı"},
                new District { CityId=3,DistrictName="Şuhut"},
                new District { CityId=4,DistrictName="Diyadin"},
                new District { CityId=4,DistrictName="Doğubeyazıt"},
                new District { CityId=4,DistrictName="Eleşkirt"},
                new District { CityId=4,DistrictName="Hamur"},
                new District { CityId=4,DistrictName="Merkez"},
                new District { CityId=4,DistrictName="Patnos"},
                new District { CityId=4,DistrictName="Taşlıçay"},
                new District { CityId=4,DistrictName="Tutak"},
                new District { CityId=7,DistrictName="Akseki"},
                new District { CityId=7,DistrictName="Aksu"},
                new District { CityId=7,DistrictName="Alanya"},
                new District { CityId=7,DistrictName="Demre"},
                new District { CityId=7,DistrictName="Döşemealtı"},
                new District { CityId=7,DistrictName="Elmalı"},
                new District { CityId=7,DistrictName="Finike"},
                new District { CityId=7,DistrictName="Gazipaşa"},
                new District { CityId=7,DistrictName="Gündoğmuş"},
                new District { CityId=7,DistrictName="İbradı"},
                new District { CityId=7,DistrictName="Kaş"},
                new District { CityId=7,DistrictName="Kemer"},
                new District { CityId=7,DistrictName="Kepez"},
                new District { CityId=7,DistrictName="Konyaaltı"},
                new District { CityId=7,DistrictName="Korkuteli"},
                new District { CityId=7,DistrictName="Kumluca"},
                new District { CityId=7,DistrictName="Manavgat"},
                new District { CityId=7,DistrictName="Merkez"},
                new District { CityId=7,DistrictName="Muratpaşa"},
                new District { CityId=7,DistrictName="Serik"},
                new District { CityId=8,DistrictName="Ardanuç"},
                new District { CityId=8,DistrictName="Arhavi"},
                new District { CityId=8,DistrictName="Borçka"},
                new District { CityId=8,DistrictName="Hopa"},
                new District { CityId=8,DistrictName="Merkez"},
                new District { CityId=8,DistrictName="Murgul (Göktaşı)"},
                new District { CityId=8,DistrictName="Şavşat"},
                new District { CityId=8,DistrictName="Yusufeli"},
                new District { CityId=9,DistrictName="Altınkum (Yenihisar)"},
                new District { CityId=9,DistrictName="Bağarası"},
                new District { CityId=9,DistrictName="Bozdoğan"},
                new District { CityId=9,DistrictName="Buharkent"},
                new District { CityId=9,DistrictName="Çine"},
                new District { CityId=9,DistrictName="Didim"},
                new District { CityId=9,DistrictName="Efeler"},
                new District { CityId=9,DistrictName="Germencik"},
                new District { CityId=9,DistrictName="İncirliova"},
                new District { CityId=9,DistrictName="Karacasu"},
                new District { CityId=9,DistrictName="Karpuzlu"},
                new District { CityId=9,DistrictName="Koçarlı"},
                new District { CityId=9,DistrictName="Köşk"},
                new District { CityId=9,DistrictName="Kuşadası"},
                new District { CityId=9,DistrictName="Kuyucak"},
                new District { CityId=9,DistrictName="Merkez"},
                new District { CityId=9,DistrictName="Nazilli"},
                new District { CityId=9,DistrictName="Ortaklar"},
                new District { CityId=9,DistrictName="Söke"},
                new District { CityId=9,DistrictName="Sultanhisar"},
                new District { CityId=9,DistrictName="Yenipazar"},
                new District { CityId=10,DistrictName="Altıeylül"},
                new District { CityId=10,DistrictName="Ayvalık"},
                new District { CityId=10,DistrictName="Balya"},
                new District { CityId=10,DistrictName="Bandırma"},
                new District { CityId=10,DistrictName="Bigadiç"},
                new District { CityId=10,DistrictName="Burhaniye"},
                new District { CityId=10,DistrictName="Dursunbey"},
                new District { CityId=10,DistrictName="Edremit"},
                new District { CityId=10,DistrictName="Erdek"},
                new District { CityId=10,DistrictName="Gömeç"},
                new District { CityId=10,DistrictName="Gönen"},
                new District { CityId=10,DistrictName="Havran"},
                new District { CityId=10,DistrictName="İvrindi"},
                new District { CityId=10,DistrictName="Karesi"},
                new District { CityId=10,DistrictName="Kepsut"},
                new District { CityId=10,DistrictName="Manyas"},
                new District { CityId=10,DistrictName="Marmara"},
                new District { CityId=10,DistrictName="Merkez"},
                new District { CityId=10,DistrictName="Savaştepe"},
                new District { CityId=10,DistrictName="Sındırgı"},
                new District { CityId=10,DistrictName="Susurluk"},
                new District { CityId=10,DistrictName="Tatlısu"},
                new District { CityId=10,DistrictName="Turkeli (Avşa)"},
                new District { CityId=11,DistrictName="Bozüyük"},
                new District { CityId=11,DistrictName="Gölpazarı"},
                new District { CityId=11,DistrictName="İnhisar"},
                new District { CityId=11,DistrictName="Merkez"},
                new District { CityId=11,DistrictName="Osmaneli"},
                new District { CityId=11,DistrictName="Pazaryeri"},
                new District { CityId=11,DistrictName="Söğüt"},
                new District { CityId=11,DistrictName="Yenipazar"},
                new District { CityId=12,DistrictName="Adaklı"},
                new District { CityId=12,DistrictName="Genç"},
                new District { CityId=12,DistrictName="Karlıova"},
                new District { CityId=12,DistrictName="Kığı"},
                new District { CityId=12,DistrictName="Merkez"},
                new District { CityId=12,DistrictName="Solhan"},
                new District { CityId=12,DistrictName="Yayladere"},
                new District { CityId=12,DistrictName="Yedisu"},
                new District { CityId=14,DistrictName="Dörtdivan"},
                new District { CityId=14,DistrictName="Gerede"},
                new District { CityId=14,DistrictName="Göynük"},
                new District { CityId=14,DistrictName="Kıbrıscık"},
                new District { CityId=14,DistrictName="Mengen"},
                new District { CityId=14,DistrictName="Merkez"},
                new District { CityId=14,DistrictName="Mudurnu"},
                new District { CityId=14,DistrictName="Seben"},
                new District { CityId=14,DistrictName="Yeniçağa"},
                new District { CityId=15,DistrictName="Ağlasun"},
                new District { CityId=15,DistrictName="Bucak"},
                new District { CityId=15,DistrictName="Çavdır"},
                new District { CityId=15,DistrictName="Çeltikçi"},
                new District { CityId=15,DistrictName="Dirmil (Altınyayla)"},
                new District { CityId=15,DistrictName="Gölhisar"},
                new District { CityId=15,DistrictName="Karamanlı"},
                new District { CityId=15,DistrictName="Kemer"},
                new District { CityId=15,DistrictName="Merkez"},
                new District { CityId=15,DistrictName="Tefenni"},
                new District { CityId=15,DistrictName="Yeşilova"},
                new District { CityId=17,DistrictName="Ayvacık"},
                new District { CityId=17,DistrictName="Bayramiç"},
                new District { CityId=17,DistrictName="Biga"},
                new District { CityId=17,DistrictName="Bozcaada"},
                new District { CityId=17,DistrictName="Çan"},
                new District { CityId=17,DistrictName="Eceabat"},
                new District { CityId=17,DistrictName="Ezine"},
                new District { CityId=17,DistrictName="Gelibolu"},
                new District { CityId=17,DistrictName="Gökçeada (İmroz)"},
                new District { CityId=17,DistrictName="Lapseki"},
                new District { CityId=17,DistrictName="Merkez"},
                new District { CityId=17,DistrictName="Yenice"},
                new District { CityId=18,DistrictName="Atkaracalar"},
                new District { CityId=18,DistrictName="Bayramören"},
                new District { CityId=18,DistrictName="Çerkeş"},
                new District { CityId=18,DistrictName="Eldivan"},
                new District { CityId=18,DistrictName="Ilgaz"},
                new District { CityId=18,DistrictName="Kızılırmak"},
                new District { CityId=18,DistrictName="Korgun"},
                new District { CityId=18,DistrictName="Kurşunlu"},
                new District { CityId=18,DistrictName="Merkez"},
                new District { CityId=18,DistrictName="Orta"},
                new District { CityId=18,DistrictName="Şabanözü"},
                new District { CityId=18,DistrictName="Yapraklı"},
                new District { CityId=19,DistrictName="Alaca"},
                new District { CityId=19,DistrictName="Bayat"},
                new District { CityId=19,DistrictName="Boğazkale"},
                new District { CityId=19,DistrictName="Dodurga"},
                new District { CityId=19,DistrictName="İskilip"},
                new District { CityId=19,DistrictName="Kargı"},
                new District { CityId=19,DistrictName="Laçin"},
                new District { CityId=19,DistrictName="Mecitözü"},
                new District { CityId=19,DistrictName="Merkez"},
                new District { CityId=19,DistrictName="Oğuzlar (Karaören)"},
                new District { CityId=19,DistrictName="Ortaköy"},
                new District { CityId=19,DistrictName="Osmancık"},
                new District { CityId=19,DistrictName="Sungurlu"},
                new District { CityId=19,DistrictName="Uğurludağ"},
                new District { CityId=20,DistrictName="Acıpayam"},
                new District { CityId=20,DistrictName="Akköy"},
                new District { CityId=20,DistrictName="Babadağ"},
                new District { CityId=20,DistrictName="Baklan"},
                new District { CityId=20,DistrictName="Bekilli"},
                new District { CityId=20,DistrictName="Beyağaç"},
                new District { CityId=20,DistrictName="Bozkurt"},
                new District { CityId=20,DistrictName="Buldan"},
                new District { CityId=20,DistrictName="Çal"},
                new District { CityId=20,DistrictName="Çameli"},
                new District { CityId=20,DistrictName="Çamlık"},
                new District { CityId=20,DistrictName="Çardak"},
                new District { CityId=20,DistrictName="Çivril"},
                new District { CityId=20,DistrictName="Güney"},
                new District { CityId=20,DistrictName="Honaz"},
                new District { CityId=20,DistrictName="Kale"},
                new District { CityId=20,DistrictName="Merkez"},
                new District { CityId=20,DistrictName="Merkezefendi"},
                new District { CityId=20,DistrictName="Pamukkale"},
                new District { CityId=20,DistrictName="Sarayköy"},
                new District { CityId=20,DistrictName="Serinhisar"},
                new District { CityId=20,DistrictName="Tavas"},
                new District { CityId=23,DistrictName="Ağın"},
                new District { CityId=23,DistrictName="Alacakaya"},
                new District { CityId=23,DistrictName="Arıcak"},
                new District { CityId=23,DistrictName="Baskil"},
                new District { CityId=23,DistrictName="Karakoçan"},
                new District { CityId=23,DistrictName="Keban"},
                new District { CityId=23,DistrictName="Kovancılar"},
                new District { CityId=23,DistrictName="Maden"},
                new District { CityId=23,DistrictName="Merkez"},
                new District { CityId=23,DistrictName="Palu"},
                new District { CityId=23,DistrictName="Sivrice"},
                new District { CityId=26,DistrictName="Alpu"},
                new District { CityId=26,DistrictName="Beylikahır(B.Ova)"},
                new District { CityId=26,DistrictName="Çifteler"},
                new District { CityId=26,DistrictName="Günyüzü"},
                new District { CityId=26,DistrictName="Han"},
                new District { CityId=26,DistrictName="İnönü"},
                new District { CityId=26,DistrictName="Mahmudiye"},
                new District { CityId=26,DistrictName="Merkez"},
                new District { CityId=26,DistrictName="Mihalgazi"},
                new District { CityId=26,DistrictName="Mihaliçcık"},
                new District { CityId=26,DistrictName="Odunpazarı"},
                new District { CityId=26,DistrictName="Sarıcakaya"},
                new District { CityId=26,DistrictName="Seyitgazi"},
                new District { CityId=26,DistrictName="Sivrihisar"},
                new District { CityId=26,DistrictName="Tepebaşı"},
                new District { CityId=27,DistrictName="Araban"},
                new District { CityId=27,DistrictName="Barak"},
                new District { CityId=27,DistrictName="Başpınar"},
                new District { CityId=27,DistrictName="Islahiye"},
                new District { CityId=27,DistrictName="Karkamış"},
                new District { CityId=27,DistrictName="Merkez"},
                new District { CityId=27,DistrictName="Nizip"},
                new District { CityId=27,DistrictName="Nurdağı"},
                new District { CityId=27,DistrictName="Oğuzeli"},
                new District { CityId=27,DistrictName="Şahinbey"},
                new District { CityId=27,DistrictName="Şehitkamil"},
                new District { CityId=27,DistrictName="Yavuzeli"},
                new District { CityId=28,DistrictName="Alucra"},
                new District { CityId=28,DistrictName="Bulancak"},
                new District { CityId=28,DistrictName="Çamoluk"},
                new District { CityId=28,DistrictName="Çanakçı"},
                new District { CityId=28,DistrictName="Dereli"},
                new District { CityId=28,DistrictName="Doğankent"},
                new District { CityId=28,DistrictName="Espiye"},
                new District { CityId=28,DistrictName="Eynesil"},
                new District { CityId=28,DistrictName="Görele"},
                new District { CityId=28,DistrictName="Güce"},
                new District { CityId=28,DistrictName="Keşap"},
                new District { CityId=28,DistrictName="Merkez"},
                new District { CityId=28,DistrictName="Piraziz"},
                new District { CityId=28,DistrictName="Şebinkarahisar"},
                new District { CityId=28,DistrictName="Tirebolu"},
                new District { CityId=28,DistrictName="Yağlıdere"},
                new District { CityId=29,DistrictName="Kelkit"},
                new District { CityId=29,DistrictName="Köse"},
                new District { CityId=29,DistrictName="Kürtün"},
                new District { CityId=29,DistrictName="Merkez"},
                new District { CityId=29,DistrictName="Şiran"},
                new District { CityId=29,DistrictName="Torul"},
                new District { CityId=30,DistrictName="Çukurca"},
                new District { CityId=30,DistrictName="Merkez"},
                new District { CityId=30,DistrictName="Şemdinli"},
                new District { CityId=30,DistrictName="Yüksekova"},
                new District { CityId=31,DistrictName="Altınözü"},
                new District { CityId=31,DistrictName="Antakya"},
                new District { CityId=31,DistrictName="Arsuz"},
                new District { CityId=31,DistrictName="Belen"},
                new District { CityId=31,DistrictName="Defne"},
                new District { CityId=31,DistrictName="Dörtyol"},
                new District { CityId=31,DistrictName="Erzin"},
                new District { CityId=31,DistrictName="Hassa"},
                new District { CityId=31,DistrictName="İskenderun"},
                new District { CityId=31,DistrictName="Kırıkhan"},
                new District { CityId=31,DistrictName="Kumlu"},
                new District { CityId=31,DistrictName="Merkez"},
                new District { CityId=31,DistrictName="Payas"},
                new District { CityId=31,DistrictName="Reyhanlı"},
                new District { CityId=31,DistrictName="Samandağ"},
                new District { CityId=31,DistrictName="Yayladağı"},
                new District { CityId=32,DistrictName="Aksu"},
                new District { CityId=32,DistrictName="Atabey"},
                new District { CityId=32,DistrictName="Eğirdir"},
                new District { CityId=32,DistrictName="Gelendost"},
                new District { CityId=32,DistrictName="Gönen"},
                new District { CityId=32,DistrictName="Keçiborlu"},
                new District { CityId=32,DistrictName="Merkez"},
                new District { CityId=32,DistrictName="Senirkent"},
                new District { CityId=32,DistrictName="Sütçüler"},
                new District { CityId=32,DistrictName="Şarkikaraağaç"},
                new District { CityId=32,DistrictName="Uluborlu"},
                new District { CityId=32,DistrictName="Yalvaç"},
                new District { CityId=32,DistrictName="Yenişarbademli"},
                new District { CityId=33,DistrictName="Anamur"},
                new District { CityId=33,DistrictName="Aydıncık"},
                new District { CityId=33,DistrictName="Bozyazı"},
                new District { CityId=33,DistrictName="Çamlıbel"},
                new District { CityId=33,DistrictName="Çamlıyayla"},
                new District { CityId=33,DistrictName="Erdemli"},
                new District { CityId=33,DistrictName="Gülnar"},
                new District { CityId=33,DistrictName="Merkez"},
                new District { CityId=33,DistrictName="Mezitli"},
                new District { CityId=33,DistrictName="Mut"},
                new District { CityId=33,DistrictName="Silifke"},
                new District { CityId=33,DistrictName="Tarsus"},
                new District { CityId=33,DistrictName="Toroslar"},
                new District { CityId=33,DistrictName="Yenişehir"},
                new District { CityId=36,DistrictName="Akyaka"},
                new District { CityId=36,DistrictName="Arpaçay"},
                new District { CityId=36,DistrictName="Digor"},
                new District { CityId=36,DistrictName="Kağızman"},
                new District { CityId=36,DistrictName="Merkez"},
                new District { CityId=36,DistrictName="Ortahisar"},
                new District { CityId=36,DistrictName="Sarıkamış"},
                new District { CityId=36,DistrictName="Selim"},
                new District { CityId=36,DistrictName="Susuz"},
                new District { CityId=37,DistrictName="Abana"},
                new District { CityId=37,DistrictName="Ağlı"},
                new District { CityId=37,DistrictName="Araç"},
                new District { CityId=37,DistrictName="Azdavay"},
                new District { CityId=37,DistrictName="Bozkurt"},
                new District { CityId=37,DistrictName="Cide"},
                new District { CityId=37,DistrictName="Çatalzeytin"},
                new District { CityId=37,DistrictName="Daday"},
                new District { CityId=37,DistrictName="Devrekani"},
                new District { CityId=37,DistrictName="Doğanyurt"},
                new District { CityId=37,DistrictName="Hanönü (Gökçeağaç)"},
                new District { CityId=37,DistrictName="İhsangazi"},
                new District { CityId=37,DistrictName="İnebolu"},
                new District { CityId=37,DistrictName="Küre"},
                new District { CityId=37,DistrictName="Merkez"},
                new District { CityId=37,DistrictName="Pınarbaşı"},
                new District { CityId=37,DistrictName="Seydiler"},
                new District { CityId=37,DistrictName="Şenpazar"},
                new District { CityId=37,DistrictName="Taşköprü"},
                new District { CityId=37,DistrictName="Tosya"},
                new District { CityId=38,DistrictName="Akkışla"},
                new District { CityId=38,DistrictName="Bünyan"},
                new District { CityId=38,DistrictName="Develi"},
                new District { CityId=38,DistrictName="Felahiye"},
                new District { CityId=38,DistrictName="Hacılar"},
                new District { CityId=38,DistrictName="İncesu"},
                new District { CityId=38,DistrictName="Kocasinan"},
                new District { CityId=38,DistrictName="Melikgazi"},
                new District { CityId=38,DistrictName="Merkez"},
                new District { CityId=38,DistrictName="Özvatan (Çukur)"},
                new District { CityId=38,DistrictName="Pınarbaşı"},
                new District { CityId=38,DistrictName="Sarıoğlan"},
                new District { CityId=38,DistrictName="Sarız"},
                new District { CityId=38,DistrictName="Talas"},
                new District { CityId=38,DistrictName="Tomarza"},
                new District { CityId=38,DistrictName="Yahyalı"},
                new District { CityId=38,DistrictName="Yeşilhisar"},
                new District { CityId=39,DistrictName="Babaeski"},
                new District { CityId=39,DistrictName="Demirköy"},
                new District { CityId=39,DistrictName="Kofçaz"},
                new District { CityId=39,DistrictName="Lüleburgaz"},
                new District { CityId=39,DistrictName="Merkez"},
                new District { CityId=39,DistrictName="Pehlivanköy"},
                new District { CityId=39,DistrictName="Pınarhisar"},
                new District { CityId=39,DistrictName="Vize"},
                new District { CityId=41,DistrictName="Başiskele"},
                new District { CityId=41,DistrictName="Çayırova"},
                new District { CityId=41,DistrictName="Darıca"},
                new District { CityId=41,DistrictName="Derince"},
                new District { CityId=41,DistrictName="Dilovası"},
                new District { CityId=41,DistrictName="Gebze"},
                new District { CityId=41,DistrictName="Gölcük"},
                new District { CityId=41,DistrictName="İzmit"},
                new District { CityId=41,DistrictName="Kandıra"},
                new District { CityId=41,DistrictName="Karamürsel"},
                new District { CityId=41,DistrictName="Kartepe"},
                new District { CityId=41,DistrictName="Körfez"},
                new District { CityId=42,DistrictName="Ahırlı"},
                new District { CityId=42,DistrictName="Akören"},
                new District { CityId=42,DistrictName="Akşehir"},
                new District { CityId=42,DistrictName="Altınekin"},
                new District { CityId=42,DistrictName="Beyşehir"},
                new District { CityId=42,DistrictName="Bozkır"},
                new District { CityId=42,DistrictName="Cihanbeyli"},
                new District { CityId=42,DistrictName="Çeltik"},
                new District { CityId=42,DistrictName="Çumra"},
                new District { CityId=42,DistrictName="Derbent"},
                new District { CityId=42,DistrictName="Derebucak"},
                new District { CityId=42,DistrictName="Doğanhisar"},
                new District { CityId=42,DistrictName="Emirgazi"},
                new District { CityId=42,DistrictName="Ereğli"},
                new District { CityId=42,DistrictName="Güneysınır"},
                new District { CityId=42,DistrictName="Hadım"},
                new District { CityId=42,DistrictName="Halkapınar"},
                new District { CityId=42,DistrictName="Hüyük"},
                new District { CityId=42,DistrictName="Ilgın"},
                new District { CityId=42,DistrictName="İçeriçumra"},
                new District { CityId=42,DistrictName="Kadınhanı"},
                new District { CityId=42,DistrictName="Karapınar"},
                new District { CityId=42,DistrictName="Karatay"},
                new District { CityId=42,DistrictName="Kulu"},
                new District { CityId=42,DistrictName="Meram"},
                new District { CityId=42,DistrictName="Merkez"},
                new District { CityId=42,DistrictName="Nalçacı"},
                new District { CityId=42,DistrictName="Sarayönü"},
                new District { CityId=42,DistrictName="Selçuklu"},
                new District { CityId=42,DistrictName="Seydişehir"},
                new District { CityId=42,DistrictName="Taşkent"},
                new District { CityId=42,DistrictName="Tuzlukçu"},
                new District { CityId=42,DistrictName="Yalıhöyük"},
                new District { CityId=42,DistrictName="Yunak"},
                new District { CityId=44,DistrictName="Akçadağ"},
                new District { CityId=44,DistrictName="Arapkir"},
                new District { CityId=44,DistrictName="Arguvan"},
                new District { CityId=44,DistrictName="Battalgazi"},
                new District { CityId=44,DistrictName="Darende"},
                new District { CityId=44,DistrictName="Doğanşehir"},
                new District { CityId=44,DistrictName="Doğanyol"},
                new District { CityId=44,DistrictName="Hekimhan"},
                new District { CityId=44,DistrictName="Kale"},
                new District { CityId=44,DistrictName="Kuluncak"},
                new District { CityId=44,DistrictName="Merkez"},
                new District { CityId=44,DistrictName="Pötürge"},
                new District { CityId=44,DistrictName="Yazıhan"},
                new District { CityId=44,DistrictName="Yeşilyurt"},
                new District { CityId=45,DistrictName="Ahmetli"},
                new District { CityId=45,DistrictName="Akhisar"},
                new District { CityId=45,DistrictName="Alaşehir"},
                new District { CityId=45,DistrictName="Demirci"},
                new District { CityId=45,DistrictName="Gölmarmara"},
                new District { CityId=45,DistrictName="Gördes"},
                new District { CityId=45,DistrictName="Kırkağaç"},
                new District { CityId=45,DistrictName="Köprübaşı"},
                new District { CityId=45,DistrictName="Kula"},
                new District { CityId=45,DistrictName="Merkez"},
                new District { CityId=45,DistrictName="Salihli"},
                new District { CityId=45,DistrictName="Sarıgöl"},
                new District { CityId=45,DistrictName="Saruhanlı"},
                new District { CityId=45,DistrictName="Selendi"},
                new District { CityId=45,DistrictName="Soma"},
                new District { CityId=45,DistrictName="Turgutlu"},
                new District { CityId=45,DistrictName="Yunus Emre"},
                new District { CityId=45,DistrictName="Zeytiova"},
                new District { CityId=46,DistrictName="Afşin"},
                new District { CityId=46,DistrictName="Andırın"},
                new District { CityId=46,DistrictName="Çağlayancerit"},
                new District { CityId=46,DistrictName="Ekinözü"},
                new District { CityId=46,DistrictName="Elbistan"},
                new District { CityId=46,DistrictName="Göksun"},
                new District { CityId=46,DistrictName="Merkez"},
                new District { CityId=46,DistrictName="Nurhak"},
                new District { CityId=46,DistrictName="Pazarcık"},
                new District { CityId=46,DistrictName="Türkoğlu"},
                new District { CityId=47,DistrictName="Dargeçit"},
                new District { CityId=47,DistrictName="Derik"},
                new District { CityId=47,DistrictName="Kızıltepe"},
                new District { CityId=47,DistrictName="Mazıdağı"},
                new District { CityId=47,DistrictName="Merkez"},
                new District { CityId=47,DistrictName="Midyat"},
                new District { CityId=47,DistrictName="Nusaybin"},
                new District { CityId=47,DistrictName="Ömerli"},
                new District { CityId=47,DistrictName="Savur"},
                new District { CityId=47,DistrictName="Yeşilli"},
                new District { CityId=48,DistrictName="Bodrum"},
                new District { CityId=48,DistrictName="Dalaman"},
                new District { CityId=48,DistrictName="Datça"},
                new District { CityId=48,DistrictName="Fethiye"},
                new District { CityId=48,DistrictName="Kavaklıdere"},
                new District { CityId=48,DistrictName="Köyceğiz"},
                new District { CityId=48,DistrictName="Marmaris"},
                new District { CityId=48,DistrictName="Merkez"},
                new District { CityId=48,DistrictName="Milas"},
                new District { CityId=48,DistrictName="Ortaca"},
                new District { CityId=48,DistrictName="Ula"},
                new District { CityId=48,DistrictName="Yatağan"},
                new District { CityId=48,DistrictName="Yerkesık"},
                new District { CityId=49,DistrictName="Bulanık"},
                new District { CityId=49,DistrictName="Hasköy"},
                new District { CityId=49,DistrictName="Korkut"},
                new District { CityId=49,DistrictName="Malazgirt"},
                new District { CityId=49,DistrictName="Merkez"},
                new District { CityId=49,DistrictName="Varto"},
                new District { CityId=51,DistrictName="Altunhisar"},
                new District { CityId=51,DistrictName="Bor"},
                new District { CityId=51,DistrictName="Çamardı"},
                new District { CityId=51,DistrictName="Çiftlik (Özyurt)"},
                new District { CityId=51,DistrictName="Merkez"},
                new District { CityId=51,DistrictName="Ulukışla"},
                new District { CityId=52,DistrictName="Akkuş"},
                new District { CityId=52,DistrictName="Aybastı"},
                new District { CityId=52,DistrictName="Çamaş"},
                new District { CityId=52,DistrictName="Çatalpınar"},
                new District { CityId=52,DistrictName="Çaybaşı"},
                new District { CityId=52,DistrictName="Fatsa"},
                new District { CityId=52,DistrictName="Gölköy"},
                new District { CityId=52,DistrictName="Gülyalı"},
                new District { CityId=52,DistrictName="Gürgentepe"},
                new District { CityId=52,DistrictName="İkizce"},
                new District { CityId=52,DistrictName="Kabadüz"},
                new District { CityId=52,DistrictName="Kabataş"},
                new District { CityId=52,DistrictName="Korgan"},
                new District { CityId=52,DistrictName="Kumru"},
                new District { CityId=52,DistrictName="Merkez"},
                new District { CityId=52,DistrictName="Mesudiye"},
                new District { CityId=52,DistrictName="Perşembe"},
                new District { CityId=52,DistrictName="Ulubey"},
                new District { CityId=52,DistrictName="Ünye"},
                new District { CityId=53,DistrictName="Ardeşen"},
                new District { CityId=53,DistrictName="Çamlıhemşin"},
                new District { CityId=53,DistrictName="Çayeli"},
                new District { CityId=53,DistrictName="Derepazarı"},
                new District { CityId=53,DistrictName="Fındıklı"},
                new District { CityId=53,DistrictName="Gündoğdu"},
                new District { CityId=53,DistrictName="Güneysu"},
                new District { CityId=53,DistrictName="Hemşin"},
                new District { CityId=53,DistrictName="İkizdere"},
                new District { CityId=53,DistrictName="İyidere"},
                new District { CityId=53,DistrictName="Kalkandere"},
                new District { CityId=53,DistrictName="Merkez"},
                new District { CityId=53,DistrictName="Müderrisler"},
                new District { CityId=53,DistrictName="Pazar"},
                new District { CityId=53,DistrictName="Pehlivantaşı"},
                new District { CityId=54,DistrictName="Adapazarı"},
                new District { CityId=54,DistrictName="Akyazı"},
                new District { CityId=54,DistrictName="Arifiye"},
                new District { CityId=54,DistrictName="Atakum"},
                new District { CityId=54,DistrictName="Bekirpaşa"},
                new District { CityId=54,DistrictName="Erenler"},
                new District { CityId=54,DistrictName="Ferizli"},
                new District { CityId=54,DistrictName="Geyve"},
                new District { CityId=54,DistrictName="Güneşler"},
                new District { CityId=54,DistrictName="Hanlı"},
                new District { CityId=54,DistrictName="Hendek"},
                new District { CityId=54,DistrictName="Karapürçek"},
                new District { CityId=54,DistrictName="Karasu"},
                new District { CityId=54,DistrictName="Kaynarca"},
                new District { CityId=54,DistrictName="Kazımpaşa"},
                new District { CityId=54,DistrictName="Kocaali"},
                new District { CityId=54,DistrictName="Nehirkent"},
                new District { CityId=54,DistrictName="Pamukova"},
                new District { CityId=54,DistrictName="Sapanca"},
                new District { CityId=54,DistrictName="Serdivan"},
                new District { CityId=54,DistrictName="Söğütlü"},
                new District { CityId=54,DistrictName="Taraklı"},
                new District { CityId=54,DistrictName="Yazlık"},
                new District { CityId=55,DistrictName="Alaçam"},
                new District { CityId=55,DistrictName="Asarcık"},
                new District { CityId=55,DistrictName="Atakum"},
                new District { CityId=55,DistrictName="Ayvacık"},
                new District { CityId=55,DistrictName="Bafra"},
                new District { CityId=55,DistrictName="Canik"},
                new District { CityId=55,DistrictName="Çarşamba"},
                new District { CityId=55,DistrictName="Gazi"},
                new District { CityId=55,DistrictName="Havza"},
                new District { CityId=55,DistrictName="İlkadım"},
                new District { CityId=55,DistrictName="Kavak"},
                new District { CityId=55,DistrictName="Kirazlık"},
                new District { CityId=55,DistrictName="Ladik"},
                new District { CityId=55,DistrictName="Merkez"},
                new District { CityId=55,DistrictName="Ondokuzmayıs"},
                new District { CityId=55,DistrictName="Salıpazarı"},
                new District { CityId=55,DistrictName="Tekkeköy"},
                new District { CityId=55,DistrictName="Terme"},
                new District { CityId=55,DistrictName="Vezirköprü"},
                new District { CityId=55,DistrictName="Yakakent"},
                new District { CityId=56,DistrictName="Aydınlar"},
                new District { CityId=56,DistrictName="Baykan"},
                new District { CityId=56,DistrictName="Eruh"},
                new District { CityId=56,DistrictName="Kurtalan"},
                new District { CityId=56,DistrictName="Merkez"},
                new District { CityId=56,DistrictName="Pervari"},
                new District { CityId=56,DistrictName="Şirvan"},
                new District { CityId=57,DistrictName="Ayancık"},
                new District { CityId=57,DistrictName="Boyabat"},
                new District { CityId=57,DistrictName="Dikmen"},
                new District { CityId=57,DistrictName="Durağan"},
                new District { CityId=57,DistrictName="Erfelek"},
                new District { CityId=57,DistrictName="Gerze"},
                new District { CityId=57,DistrictName="Merkez"},
                new District { CityId=57,DistrictName="Saraydüzü"},
                new District { CityId=57,DistrictName="Türkeli"},
                new District { CityId=58,DistrictName="Akıncılar"},
                new District { CityId=58,DistrictName="Altınyayla"},
                new District { CityId=58,DistrictName="Divriği"},
                new District { CityId=58,DistrictName="Doğanşar"},
                new District { CityId=58,DistrictName="Gemerek"},
                new District { CityId=58,DistrictName="Gölova"},
                new District { CityId=58,DistrictName="Gürün"},
                new District { CityId=58,DistrictName="Hafik"},
                new District { CityId=58,DistrictName="İmranlı"},
                new District { CityId=58,DistrictName="Kangal"},
                new District { CityId=58,DistrictName="Koyulhisar"},
                new District { CityId=58,DistrictName="Merkez"},
                new District { CityId=58,DistrictName="Suşehri"},
                new District { CityId=58,DistrictName="Şarkışla"},
                new District { CityId=58,DistrictName="Ulaş"},
                new District { CityId=58,DistrictName="Yıldızeli"},
                new District { CityId=58,DistrictName="Zara"},
                new District { CityId=59,DistrictName="Çerkezköy"},
                new District { CityId=59,DistrictName="Çorlu"},
                new District { CityId=59,DistrictName="Ergene"},
                new District { CityId=59,DistrictName="Hayrabolu"},
                new District { CityId=59,DistrictName="Kapaklı"},
                new District { CityId=59,DistrictName="Malkara"},
                new District { CityId=59,DistrictName="Marmaraereğlisi"},
                new District { CityId=59,DistrictName="Muratlı"},
                new District { CityId=59,DistrictName="Saray"},
                new District { CityId=59,DistrictName="Süleymanpaşa"},
                new District { CityId=59,DistrictName="Şarköy"},
                new District { CityId=2,DistrictName="Besni"},
                new District { CityId=2,DistrictName="Çelikhan"},
                new District { CityId=2,DistrictName="Gerger"},
                new District { CityId=2,DistrictName="Gölbaşı"},
                new District { CityId=2,DistrictName="Kahta"},
                new District { CityId=2,DistrictName="Merkez"},
                new District { CityId=2,DistrictName="Samsat"},
                new District { CityId=2,DistrictName="Sıncık"},
                new District { CityId=2,DistrictName="Tut"},
                new District { CityId=5,DistrictName="Göynücek"},
                new District { CityId=5,DistrictName="Gümüşhacıköy"},
                new District { CityId=5,DistrictName="Hamamözü"},
                new District { CityId=5,DistrictName="Merkez"},
                new District { CityId=5,DistrictName="Merzifon"},
                new District { CityId=5,DistrictName="Suluova"},
                new District { CityId=5,DistrictName="Taşova"},
                new District { CityId=13,DistrictName="Adilcevaz"},
                new District { CityId=13,DistrictName="Ahlat"},
                new District { CityId=13,DistrictName="Güroymak (Çukur)"},
                new District { CityId=13,DistrictName="Hizan"},
                new District { CityId=13,DistrictName="Merkez"},
                new District { CityId=13,DistrictName="Mutki"},
                new District { CityId=13,DistrictName="Tatvan"},
                new District { CityId=16,DistrictName="Büyükorhan"},
                new District { CityId=16,DistrictName="Gemlik"},
                new District { CityId=16,DistrictName="Gürsu"},
                new District { CityId=16,DistrictName="Harmancık"},
                new District { CityId=16,DistrictName="İnegöl"},
                new District { CityId=16,DistrictName="İznik"},
                new District { CityId=16,DistrictName="Karacabey"},
                new District { CityId=16,DistrictName="Keles"},
                new District { CityId=16,DistrictName="Kestel"},
                new District { CityId=16,DistrictName="Küçük Kumla"},
                new District { CityId=16,DistrictName="Merkez"},
                new District { CityId=16,DistrictName="Mudanya"},
                new District { CityId=16,DistrictName="Mustafakemalpaşa"},
                new District { CityId=16,DistrictName="Nilüfer"},
                new District { CityId=16,DistrictName="Orhaneli"},
                new District { CityId=16,DistrictName="Orhangazi"},
                new District { CityId=16,DistrictName="Osmangazi"},
                new District { CityId=16,DistrictName="Yenişehir"},
                new District { CityId=16,DistrictName="Yıldırım"},
                new District { CityId=21,DistrictName="Bağlar"},
                new District { CityId=21,DistrictName="Bismil"},
                new District { CityId=21,DistrictName="Çermik"},
                new District { CityId=21,DistrictName="Çınar"},
                new District { CityId=21,DistrictName="Çüngüş"},
                new District { CityId=21,DistrictName="Dicle"},
                new District { CityId=21,DistrictName="Eğil"},
                new District { CityId=21,DistrictName="Ergani"},
                new District { CityId=21,DistrictName="Hani"},
                new District { CityId=21,DistrictName="Hazro"},
                new District { CityId=21,DistrictName="Kocaköy"},
                new District { CityId=21,DistrictName="Kulp"},
                new District { CityId=21,DistrictName="Lice"},
                new District { CityId=21,DistrictName="Merkez"},
                new District { CityId=21,DistrictName="Silvan"},
                new District { CityId=21,DistrictName="Sur"},
                new District { CityId=21,DistrictName="Yenişehir"},
                new District { CityId=22,DistrictName="Enez"},
                new District { CityId=22,DistrictName="Havsa"},
                new District { CityId=22,DistrictName="İpsala"},
                new District { CityId=22,DistrictName="Kapıkule"},
                new District { CityId=22,DistrictName="Keşan"},
                new District { CityId=22,DistrictName="Lalapaşa"},
                new District { CityId=22,DistrictName="Meriç"},
                new District { CityId=22,DistrictName="Merkez"},
                new District { CityId=22,DistrictName="Süleoğlu"},
                new District { CityId=22,DistrictName="Uzunköprü"},
                new District { CityId=24,DistrictName="Çayırlı"},
                new District { CityId=24,DistrictName="İliç"},
                new District { CityId=24,DistrictName="Kemah"},
                new District { CityId=24,DistrictName="Kemaliye"},
                new District { CityId=24,DistrictName="Merkez"},
                new District { CityId=24,DistrictName="Otlukbeli"},
                new District { CityId=24,DistrictName="Refahiye"},
                new District { CityId=24,DistrictName="Tercan"},
                new District { CityId=24,DistrictName="Üzümlü"},
                new District { CityId=25,DistrictName="Aşkale"},
                new District { CityId=25,DistrictName="Çat"},
                new District { CityId=25,DistrictName="Hınıs"},
                new District { CityId=25,DistrictName="Horasan"},
                new District { CityId=25,DistrictName="Ilıca"},
                new District { CityId=25,DistrictName="İspir"},
                new District { CityId=25,DistrictName="Karaçoban"},
                new District { CityId=25,DistrictName="Karakocan"},
                new District { CityId=25,DistrictName="Karayazı"},
                new District { CityId=25,DistrictName="Kazımkarabekir"},
                new District { CityId=25,DistrictName="Köprüköy"},
                new District { CityId=25,DistrictName="Merkez"},
                new District { CityId=25,DistrictName="Narman"},
                new District { CityId=25,DistrictName="Oltu"},
                new District { CityId=25,DistrictName="Olur"},
                new District { CityId=25,DistrictName="Palandöken"},
                new District { CityId=25,DistrictName="Pasinler"},
                new District { CityId=25,DistrictName="Pazaryolu"},
                new District { CityId=25,DistrictName="Şenkaya"},
                new District { CityId=25,DistrictName="Tekman"},
                new District { CityId=25,DistrictName="Tortum"},
                new District { CityId=25,DistrictName="Uzundere"},
                new District { CityId=40,DistrictName="Akçakent"},
                new District { CityId=40,DistrictName="Akpınar"},
                new District { CityId=40,DistrictName="Boztepe"},
                new District { CityId=40,DistrictName="Çiçekdağı"},
                new District { CityId=40,DistrictName="Kaman"},
                new District { CityId=40,DistrictName="Merkez"},
                new District { CityId=40,DistrictName="Mucur"},
                new District { CityId=43,DistrictName="Altıntaş"},
                new District { CityId=43,DistrictName="Aslanapa"},
                new District { CityId=43,DistrictName="Çavdarhisar"},
                new District { CityId=43,DistrictName="Domaniç"},
                new District { CityId=43,DistrictName="Dumlupınar"},
                new District { CityId=43,DistrictName="Emet"},
                new District { CityId=43,DistrictName="Gediz"},
                new District { CityId=43,DistrictName="Hisarcık"},
                new District { CityId=43,DistrictName="Merkez"},
                new District { CityId=43,DistrictName="Pazarlar"},
                new District { CityId=43,DistrictName="Simav"},
                new District { CityId=43,DistrictName="Şaphane"},
                new District { CityId=43,DistrictName="Tavşanlı"},
                new District { CityId=50,DistrictName="Acıgöl"},
                new District { CityId=50,DistrictName="Avanos"},
                new District { CityId=50,DistrictName="Derinkuyu"},
                new District { CityId=50,DistrictName="Gülşehir"},
                new District { CityId=50,DistrictName="Hacıbektaş"},
                new District { CityId=50,DistrictName="Kozaklı"},
                new District { CityId=50,DistrictName="Merkez"},
                new District { CityId=50,DistrictName="Ürgüp"},
                new District { CityId=60,DistrictName="Almus"},
                new District { CityId=60,DistrictName="Artova"},
                new District { CityId=60,DistrictName="Başçiftlik"},
                new District { CityId=60,DistrictName="Erbaa"},
                new District { CityId=60,DistrictName="Merkez"},
                new District { CityId=60,DistrictName="Niksar"},
                new District { CityId=60,DistrictName="Pazar"},
                new District { CityId=60,DistrictName="Reşadiye"},
                new District { CityId=60,DistrictName="Sulusaray"},
                new District { CityId=60,DistrictName="Turhal"},
                new District { CityId=60,DistrictName="Yeşilyurt"},
                new District { CityId=60,DistrictName="Zile"},
                new District { CityId=61,DistrictName="Akçaabat"},
                new District { CityId=61,DistrictName="Araklı"},
                new District { CityId=61,DistrictName="Arsin"},
                new District { CityId=61,DistrictName="Beşikdüzü"},
                new District { CityId=61,DistrictName="Çarşıbaşı"},
                new District { CityId=61,DistrictName="Çaykara"},
                new District { CityId=61,DistrictName="Dernekpazarı"},
                new District { CityId=61,DistrictName="Düzköy"},
                new District { CityId=61,DistrictName="Hayrat"},
                new District { CityId=61,DistrictName="Köprübaşı"},
                new District { CityId=61,DistrictName="Maçka"},
                new District { CityId=61,DistrictName="Merkez"},
                new District { CityId=61,DistrictName="Of"},
                new District { CityId=61,DistrictName="Ortahisar"},
                new District { CityId=61,DistrictName="Sürmene"},
                new District { CityId=61,DistrictName="Şalpazarı"},
                new District { CityId=61,DistrictName="Taşhanpazarı"},
                new District { CityId=61,DistrictName="Tonya"},
                new District { CityId=61,DistrictName="Vakfıkebir"},
                new District { CityId=61,DistrictName="Yomra"},
                new District { CityId=62,DistrictName="Çemişgezek"},
                new District { CityId=62,DistrictName="Hozat"},
                new District { CityId=62,DistrictName="Mazgirt"},
                new District { CityId=62,DistrictName="Merkez"},
                new District { CityId=62,DistrictName="Nazımiye"},
                new District { CityId=62,DistrictName="Ovacık"},
                new District { CityId=62,DistrictName="Pertek"},
                new District { CityId=62,DistrictName="Pülümür"},
                new District { CityId=63,DistrictName="Akçakale"},
                new District { CityId=63,DistrictName="Birecik"},
                new District { CityId=63,DistrictName="Bozova"},
                new District { CityId=63,DistrictName="Ceylanpınar"},
                new District { CityId=63,DistrictName="Eyyübiye"},
                new District { CityId=63,DistrictName="Halfeti"},
                new District { CityId=63,DistrictName="Harran"},
                new District { CityId=63,DistrictName="Hilvan"},
                new District { CityId=63,DistrictName="Merkez"},
                new District { CityId=63,DistrictName="Siverek"},
                new District { CityId=63,DistrictName="Suruç"},
                new District { CityId=63,DistrictName="Viranşehir"},
                new District { CityId=67,DistrictName="Alaplı"},
                new District { CityId=67,DistrictName="Beycuma"},
                new District { CityId=67,DistrictName="Çatalağzı"},
                new District { CityId=67,DistrictName="Çaycuma"},
                new District { CityId=67,DistrictName="Devrek"},
                new District { CityId=67,DistrictName="Ereğli"},
                new District { CityId=67,DistrictName="Gökçebey"},
                new District { CityId=67,DistrictName="Hisarönü (Filyos)"},
                new District { CityId=67,DistrictName="Kandilli (Armutçuk)"},
                new District { CityId=67,DistrictName="Karadeniz Ereğli"},
                new District { CityId=67,DistrictName="Kilimli"},
                new District { CityId=67,DistrictName="Kozlu"},
                new District { CityId=67,DistrictName="Merkez"},
                new District { CityId=66,DistrictName="Akdağmadeni"},
                new District { CityId=66,DistrictName="Aydıncık"},
                new District { CityId=66,DistrictName="Boğazlıyan"},
                new District { CityId=66,DistrictName="Çandır"},
                new District { CityId=66,DistrictName="Çayıralan"},
                new District { CityId=66,DistrictName="Çekerek"},
                new District { CityId=66,DistrictName="Kadışehri"},
                new District { CityId=66,DistrictName="Merkez"},
                new District { CityId=66,DistrictName="Saraykent"},
                new District { CityId=66,DistrictName="Sarıkaya"},
                new District { CityId=66,DistrictName="Sorgun"},
                new District { CityId=66,DistrictName="Şefaatli"},
                new District { CityId=66,DistrictName="Yenifakılı"},
                new District { CityId=66,DistrictName="Yerköy"},
                new District { CityId=65,DistrictName="Bahçesaray"},
                new District { CityId=65,DistrictName="Başkale"},
                new District { CityId=65,DistrictName="Çaldıran"},
                new District { CityId=65,DistrictName="Çatak"},
                new District { CityId=65,DistrictName="Edremit (Gümüşdere)"},
                new District { CityId=65,DistrictName="Erciş"},
                new District { CityId=65,DistrictName="Gevaş"},
                new District { CityId=65,DistrictName="Gümüşdere"},
                new District { CityId=65,DistrictName="Gürpınar"},
                new District { CityId=65,DistrictName="İpekyolu"},
                new District { CityId=65,DistrictName="Merkez"},
                new District { CityId=65,DistrictName="Muradiye"},
                new District { CityId=65,DistrictName="Özalp"},
                new District { CityId=65,DistrictName="Saray"},
                new District { CityId=65,DistrictName="Tuşba"},
                new District { CityId=64,DistrictName="Banaz"},
                new District { CityId=64,DistrictName="Eşme"},
                new District { CityId=64,DistrictName="Karahallı"},
                new District { CityId=64,DistrictName="Merkez"},
                new District { CityId=64,DistrictName="Sivaslı"},
                new District { CityId=64,DistrictName="Ulubey"},
                new District { CityId=68,DistrictName="Ağaçören"},
                new District { CityId=68,DistrictName="Eskil"},
                new District { CityId=68,DistrictName="Gülağaç (Ağaçlı)"},
                new District { CityId=68,DistrictName="Güzelyurt"},
                new District { CityId=68,DistrictName="Merkez"},
                new District { CityId=68,DistrictName="Ortaköy"},
                new District { CityId=68,DistrictName="Sarıyahşi"},
                new District { CityId=81,DistrictName="Akçakoca"},
                new District { CityId=81,DistrictName="Cumayeri"},
                new District { CityId=81,DistrictName="Çilimli"},
                new District { CityId=81,DistrictName="Gölyaka"},
                new District { CityId=81,DistrictName="Gümüşova (Cumaova)"},
                new District { CityId=81,DistrictName="Kaynaşlı"},
                new District { CityId=81,DistrictName="Merkez"},
                new District { CityId=81,DistrictName="Yığılca"},
                new District { CityId=78,DistrictName="Eflani"},
                new District { CityId=78,DistrictName="Eskipazar"},
                new District { CityId=78,DistrictName="Merkez"},
                new District { CityId=78,DistrictName="Ovacık"},
                new District { CityId=78,DistrictName="Safranbolu"},
                new District { CityId=78,DistrictName="Yenice"},
                new District { CityId=77,DistrictName="Altınova"},
                new District { CityId=77,DistrictName="Armutlu"},
                new District { CityId=77,DistrictName="Çınarcık"},
                new District { CityId=77,DistrictName="Çiftlikköy"},
                new District { CityId=77,DistrictName="Merkez"},
                new District { CityId=77,DistrictName="Termal"},
                new District { CityId=76,DistrictName="Aralık"},
                new District { CityId=76,DistrictName="Karakoyunlu"},
                new District { CityId=76,DistrictName="Merkez"},
                new District { CityId=76,DistrictName="Tuzluca"},
                new District { CityId=75,DistrictName="Çıldır"},
                new District { CityId=75,DistrictName="Damal"},
                new District { CityId=75,DistrictName="Göle"},
                new District { CityId=75,DistrictName="Hanak"},
                new District { CityId=75,DistrictName="Merkez"},
                new District { CityId=75,DistrictName="Posof"},
                new District { CityId=74,DistrictName="Amasra"},
                new District { CityId=74,DistrictName="Kurucaşile"},
                new District { CityId=74,DistrictName="Merkez"},
                new District { CityId=74,DistrictName="Ulus"},
                new District { CityId=73,DistrictName="Beytüşşebap"},
                new District { CityId=73,DistrictName="Cizre"},
                new District { CityId=73,DistrictName="Güçlükonak"},
                new District { CityId=73,DistrictName="Habur"},
                new District { CityId=73,DistrictName="İdil"},
                new District { CityId=73,DistrictName="Merkez"},
                new District { CityId=73,DistrictName="Silopi"},
                new District { CityId=73,DistrictName="Uludere"},
                new District { CityId=72,DistrictName="Beşiri"},
                new District { CityId=72,DistrictName="Gercüş"},
                new District { CityId=72,DistrictName="Hasankeyf"},
                new District { CityId=72,DistrictName="Kozluk"},
                new District { CityId=72,DistrictName="Merkez"},
                new District { CityId=72,DistrictName="Sason"},
                new District { CityId=71,DistrictName="Bahşılı"},
                new District { CityId=71,DistrictName="Balışeyh"},
                new District { CityId=71,DistrictName="Çelebi"},
                new District { CityId=71,DistrictName="Delice"},
                new District { CityId=71,DistrictName="Karakeçili"},
                new District { CityId=71,DistrictName="Keskin"},
                new District { CityId=71,DistrictName="Merkez"},
                new District { CityId=71,DistrictName="Sulakyurt"},
                new District { CityId=71,DistrictName="Yahşihan"},
                new District { CityId=70,DistrictName="Ayrancı"},
                new District { CityId=70,DistrictName="Başyayla"},
                new District { CityId=70,DistrictName="Ermenek"},
                new District { CityId=70,DistrictName="Kazımkarabekir"},
                new District { CityId=70,DistrictName="Merkez"},
                new District { CityId=70,DistrictName="Sarıveliler"},
                new District { CityId=69,DistrictName="Aydıntepe"},
                new District { CityId=69,DistrictName="Demirözü"},
                new District { CityId=69,DistrictName="Merkez"},
                new District { CityId=80,DistrictName="Bahçe"},
                new District { CityId=80,DistrictName="Düziçi"},
                new District { CityId=80,DistrictName="Hasanbeyli"},
                new District { CityId=80,DistrictName="Kadirli"},
                new District { CityId=80,DistrictName="Merkez"},
                new District { CityId=80,DistrictName="Sumbas"},
                new District { CityId=80,DistrictName="Toprakkale"},
                new District { CityId=79,DistrictName="Elbeyli"},
                new District { CityId=79,DistrictName="Merkez"},
                new District { CityId=79,DistrictName="Musabeyli"},
                new District { CityId=79,DistrictName="Polateli"},
            };

            await _context.Districts.AddRangeAsync(districts);
            await _context.SaveChangesAsync();
        }

        #endregion

        #region Nationalities

        if (!_context.Nationalities.Any())
        {
            var nationalities = new List<Nationality>
            {
                new Nationality{ Name = "Türkiye"},
                new Nationality{ Name = "** Diğer"},
                new Nationality{ Name = "ABD"},
                new Nationality{ Name = "Abd Virgin Adaları"},
                new Nationality{ Name = "Afganistan"},
                new Nationality{ Name = "Almanya"},
                new Nationality{ Name = "Angola"},
                new Nationality{ Name = "Anguilla"},
                new Nationality{ Name = "Antigua Ve Barbuda "},
                new Nationality{ Name = "Arjantin"},
                new Nationality{ Name = "Arnavutluk"},
                new Nationality{ Name = "Aruba"},
                new Nationality{ Name = "Avustralya"},
                new Nationality{ Name = "Avusturya"},
                new Nationality{ Name = "Azerbaycan"},
                new Nationality{ Name = "B. Virgin Adaları"},
                new Nationality{ Name = "B.A.E."},
                new Nationality{ Name = "Bahamalar"},
                new Nationality{ Name = "Bahreyn"},
                new Nationality{ Name = "Bangladeş"},
                new Nationality{ Name = "Barbados"},
                new Nationality{ Name = "Belçika"},
                new Nationality{ Name = "Beliz"},
                new Nationality{ Name = "Benin"},
                new Nationality{ Name = "Bermuda"},
                new Nationality{ Name = "Beyaz Rusya"},
                new Nationality{ Name = "Bolivya"},
                new Nationality{ Name = "Bosna-Hersek"},
                new Nationality{ Name = "Botsvana"},
                new Nationality{ Name = "Brezilya"},
                new Nationality{ Name = "Brunei Darü's-Selam"},
                new Nationality{ Name = "Bulgaristan"},
                new Nationality{ Name = "Burkina Faso"},
                new Nationality{ Name = "Burundi"},
                new Nationality{ Name = "Cayman Adaları"},
                new Nationality{ Name = "Cezayir"},
                new Nationality{ Name = "Cibuti"},
                new Nationality{ Name = "Çad"},
                new Nationality{ Name = "Çek Cumhuriyeti"},
                new Nationality{ Name = "Çin"},
                new Nationality{ Name = "Danimarka"},
                new Nationality{ Name = "Dominica"},
                new Nationality{ Name = "Dominik Cumhuriyeti"},
                new Nationality{ Name = "Ekvador"},
                new Nationality{ Name = "Ekvator Ginesi"},
                new Nationality{ Name = "El Salvador"},
                new Nationality{ Name = "Endonezya"},
                new Nationality{ Name = "Erıtre"},
                new Nationality{ Name = "Estonya"},
                new Nationality{ Name = "Etiyopya"},
                new Nationality{ Name = "Fas"},
                new Nationality{ Name = "Fiji"},
                new Nationality{ Name = "Fildişi Sahili"},
                new Nationality{ Name = "Filipinler"},
                new Nationality{ Name = "Filistin"},
                new Nationality{ Name = "Finlandiya"},
                new Nationality{ Name = "Fransa"},
                new Nationality{ Name = "Fransız Guyanası"},
                new Nationality{ Name = "G. Afrika"},
                new Nationality{ Name = "Gabon"},
                new Nationality{ Name = "Galler"},
                new Nationality{ Name = "Gambiya"},
                new Nationality{ Name = "Gana"},
                new Nationality{ Name = "Gine – Bissau"},
                new Nationality{ Name = "Gine Cumhuriyeti"},
                new Nationality{ Name = "Grenada"},
                new Nationality{ Name = "Guadalup"},
                new Nationality{ Name = "Guetemala"},
                new Nationality{ Name = "Guyana"},
                new Nationality{ Name = "Gürcistan"},
                new Nationality{ Name = "Haiti"},
                new Nationality{ Name = "Hırvatistan"},
                new Nationality{ Name = "Hindistan"},
                new Nationality{ Name = "Hollanda"},
                new Nationality{ Name = "Hollanda Antilleri"},
                new Nationality{ Name = "Honduras"},
                new Nationality{ Name = "Hong Kong"},
                new Nationality{ Name = "Irak"},
                new Nationality{ Name = "Irlanda"},
                new Nationality{ Name = "İngiltere"},
                new Nationality{ Name = "İran"},
                new Nationality{ Name = "İskoçya"},
                new Nationality{ Name = "İspanya"},
                new Nationality{ Name = "İsrail"},
                new Nationality{ Name = "İsveç"},
                new Nationality{ Name = "İsviçre"},
                new Nationality{ Name = "İtalya"},
                new Nationality{ Name = "İzlanda"},
                new Nationality{ Name = "Jamaika"},
                new Nationality{ Name = "Japonya"},
                new Nationality{ Name = "Kamboçya"},
                new Nationality{ Name = "Kamerun"},
                new Nationality{ Name = "Kanada"},
                new Nationality{ Name = "Karadağ"},
                new Nationality{ Name = "Katar"},
                new Nationality{ Name = "Kazakistan"},
                new Nationality{ Name = "Kenya"},
                new Nationality{ Name = "Kırgızistan"},
                new Nationality{ Name = "Kolombiya"},
                new Nationality{ Name = "Komorlar"},
                new Nationality{ Name = "Kongo"},
                new Nationality{ Name = "Kore"},
                new Nationality{ Name = "Kosova"},
                new Nationality{ Name = "Kosta Rika"},
                new Nationality{ Name = "Kuveyt"},
                new Nationality{ Name = "Kuzey Afrika"},
                new Nationality{ Name = "Kuzey Kıbrıs T.C"},
                new Nationality{ Name = "Küba"},
                new Nationality{ Name = "Letonya"},
                new Nationality{ Name = "Liberya"},
                new Nationality{ Name = "Libya"},
                new Nationality{ Name = "Lihtenştayn"},
                new Nationality{ Name = "Litvanya"},
                new Nationality{ Name = "Lübnan"},
                new Nationality{ Name = "Lüksemburg"},
                new Nationality{ Name = "Macaristan"},
                new Nationality{ Name = "Madagaskar"},
                new Nationality{ Name = "Makedonya"},
                new Nationality{ Name = "Malavi Cumhuriyeti"},
                new Nationality{ Name = "Maldivler"},
                new Nationality{ Name = "Malezya"},
                new Nationality{ Name = "Mali"},
                new Nationality{ Name = "Malta"},
                new Nationality{ Name = "Martinik"},
                new Nationality{ Name = "Meksika"},
                new Nationality{ Name = "Mısır"},
                new Nationality{ Name = "Moğolistan"},
                new Nationality{ Name = "Moldova"},
                new Nationality{ Name = "Monaco"},
                new Nationality{ Name = "Montserrat"},
                new Nationality{ Name = "Moris Adaları"},
                new Nationality{ Name = "Moritanya"},
                new Nationality{ Name = "Mozambik"},
                new Nationality{ Name = "Myanmar"},
                new Nationality{ Name = "Nepal"},
                new Nationality{ Name = "Nijer"},
                new Nationality{ Name = "Nijerya"},
                new Nationality{ Name = "Norveç"},
                new Nationality{ Name = "Orta Afrika Cum."},
                new Nationality{ Name = "Özbekistan"},
                new Nationality{ Name = "Pakistan"},
                new Nationality{ Name = "Panama"},
                new Nationality{ Name = "Papua Yeni Gine"},
                new Nationality{ Name = "Paraguay"},
                new Nationality{ Name = "Peru"},
                new Nationality{ Name = "Polonya"},
                new Nationality{ Name = "Portekiz"},
                new Nationality{ Name = "Porto Riko"},
                new Nationality{ Name = "Romanya"},
                new Nationality{ Name = "Ruanda Cumhuriyeti"},
                new Nationality{ Name = "Rusya"},
                new Nationality{ Name = "Saint Kitts Ve Nevis"},
                new Nationality{ Name = "Saint Lucia"},
                new Nationality{ Name = "Saint Vincents"},
                new Nationality{ Name = "Samoa"},
                new Nationality{ Name = "Senegal"},
                new Nationality{ Name = "Seyşeller"},
                new Nationality{ Name = "Sırbistan"},
                new Nationality{ Name = "Sieera Leone"},
                new Nationality{ Name = "Sierra Leone"},
                new Nationality{ Name = "Singapur"},
                new Nationality{ Name = "Slovak Cumhuriyeti"},
                new Nationality{ Name = "Slovenya"},
                new Nationality{ Name = "Somali"},
                new Nationality{ Name = "Sri Lanka"},
                new Nationality{ Name = "Sudan"},
                new Nationality{ Name = "Suriname"},
                new Nationality{ Name = "Suriye"},
                new Nationality{ Name = "Suudi Arabistan"},
                new Nationality{ Name = "Şili"},
                new Nationality{ Name = "Tacikistan"},
                new Nationality{ Name = "Tanzanya"},
                new Nationality{ Name = "Tayland"},
                new Nationality{ Name = "Tayvan"},
                new Nationality{ Name = "Trinidad Ve Tobago"},
                new Nationality{ Name = "Tunus"},
                new Nationality{ Name = "Turks Ve Caicos"},
                new Nationality{ Name = "Türkmenistan"},
                new Nationality{ Name = "Uganda"},
                new Nationality{ Name = "Ukrayna"},
                new Nationality{ Name = "Umman"},
                new Nationality{ Name = "Uruguay"},
                new Nationality{ Name = "Ürdün"},
                new Nationality{ Name = "Venezuela"},
                new Nationality{ Name = "Vietnam"},
                new Nationality{ Name = "Yemen"},
                new Nationality{ Name = "Yeni Zelanda"},
                new Nationality{ Name = "Yunanistan"},
                new Nationality{ Name = "Zaire"},
                new Nationality{ Name = "Zambia"},
                new Nationality{ Name = "Zimbabve"},
            };


            await _context.Nationalities.AddRangeAsync(nationalities);
            await _context.SaveChangesAsync();

        }

        #endregion

        #region Driving licences

        if (!_context.DrivingLicences.Any())
        {
            var drivingLicence = new List<DrivingLicence>
            {
                new DrivingLicence{ Name = "A"},
                new DrivingLicence{ Name = "A1"},
                new DrivingLicence{ Name = "A2"},
                new DrivingLicence{ Name = "B"},
                new DrivingLicence{ Name = "B2"},
                new DrivingLicence{ Name = "C"},
                new DrivingLicence{ Name = "D"},
                new DrivingLicence{ Name = "E"},
                new DrivingLicence{ Name = "F"},
                new DrivingLicence{ Name = "G"},
                new DrivingLicence{ Name = "H"},
                new DrivingLicence{ Name = "K"},
                new DrivingLicence{ Name = "U"},
            };

            await _context.DrivingLicences.AddRangeAsync(drivingLicence);
            await _context.SaveChangesAsync();
        }

        #endregion

        #region Jobs

        if (!_context.Jobs.Any())
        {
            var jobs = new List<Job>
            {
               new Job{ JobName = "Yazılım Mühendisi", JobCode = "yazilim_muhendisi" },
                new Job{ JobName = "İnsan Kaynakları Uzmanı", JobCode = "insan_kaynaklari_uzmani" },
                new Job{ JobName = "Satış Temsilcisi", JobCode = "satis_temsilcisi" },
                new Job{ JobName = "Makine Mühendisi", JobCode = "makine_muhendisi" },
                new Job{ JobName = "Proje Yöneticisi", JobCode = "proje_yoneticisi" },
                new Job{ JobName = "Muhasebe Uzmanı", JobCode = "muhasebe_uzmani" },
                new Job{ JobName = "Finans Analisti", JobCode = "finans_analisti" },
                new Job{ JobName = "Hukuk Müşaviri", JobCode = "hukuk_musaviri" },
                new Job{ JobName = "Ağ Yöneticisi", JobCode = "ag_yoneticisi" },
                new Job{ JobName = "Siber Güvenlik Uzmanı", JobCode = "siber_guvenlik_uzmani" },
                new Job{ JobName = "Pazarlama Müdürü", JobCode = "pazarlama_muduru" },
                new Job{ JobName = "İş Geliştirme Uzmanı", JobCode = "is_gelistirme_uzmani" },
                new Job{ JobName = "Endüstri Mühendisi", JobCode = "endustri_muhendisi" },
                new Job{ JobName = "Elektrik Mühendisi", JobCode = "elektrik_muhendisi" },
                new Job{ JobName = "Mekatronik Mühendisi", JobCode = "mekatronik_muhendisi" },
                new Job{ JobName = "Bilgi İşlem Destek Uzmanı", JobCode = "bilgi_islem_destek_uzmani" },
                new Job{ JobName = "Veri Bilimcisi", JobCode = "veri_bilimcisi" },
                new Job{ JobName = "Üretim Müdürü", JobCode = "uretim_muduru" },
                new Job{ JobName = "Kalite Kontrol Uzmanı", JobCode = "kalite_kontrol_uzmani" },
                new Job{ JobName = "Çevre Mühendisi", JobCode = "cevre_muhendisi" },
                new Job{ JobName = "İç Denetçi", JobCode = "ic_denetci" },
                new Job{ JobName = "İthalat İhracat Uzmanı", JobCode = "ithalat_ihracat_uzmani" },
                new Job{ JobName = "Lojistik Sorumlusu", JobCode = "lojistik_sorumlusu" },
                new Job{ JobName = "Satın Alma Uzmanı", JobCode = "satin_alma_uzmani" },
                new Job{ JobName = "ERP Danışmanı", JobCode = "erp_danismani" },
                new Job{ JobName = "Grafik Tasarımcısı", JobCode = "grafik_tasarimcisi" },
                new Job{ JobName = "Web Geliştirici", JobCode = "web_gelistirici" },
                new Job{ JobName = "Reklam ve Halkla İlişkiler Uzmanı", JobCode = "reklam_ve_halkla_iliskiler_uzmani" },
                new Job{ JobName = "SEO Uzmanı", JobCode = "seo_uzmani" },
                new Job{ JobName = "Mobil Uygulama Geliştirici", JobCode = "mobil_uygulama_gelistirici" },
                new Job{ JobName = "Data Analyst", JobCode = "data_analyst" },
                new Job{ JobName = "IT Destek Uzmanı", JobCode = "it_destek_uzmani" },
                new Job{ JobName = "Network Uzmanı", JobCode = "network_uzmani" },
                new Job{ JobName = "İş Zekası Uzmanı", JobCode = "is_zekasi_uzmani" },
                new Job{ JobName = "Sosyal Medya Uzmanı", JobCode = "sosyal_medya_uzmani" },
                new Job{ JobName = "Makine Operatörü", JobCode = "makine_operatoru" },
                new Job{ JobName = "Hastane Yöneticisi", JobCode = "hastane_yoneticisi" },
                new Job{ JobName = "Sağlık Danışmanı", JobCode = "saglik_danismani" },
                new Job{ JobName = "Müşteri İlişkileri Yöneticisi", JobCode = "musteri_iliskileri_yoneticisi" },
                new Job{ JobName = "Akademisyen", JobCode = "akademisyen" },
                new Job{ JobName = "Psikolog", JobCode = "psikolog" },
                new Job{ JobName = "Doktor", JobCode = "doktor" },
                new Job{ JobName = "Hemşire", JobCode = "hemsire" },
                new Job{ JobName = "Fizyoterapist", JobCode = "fizyoterapist" },
                new Job{ JobName = "Diş Hekimi", JobCode = "dis_hekimi" },
                new Job{ JobName = "Çocuk Gelişim Uzmanı", JobCode = "cocuk_gelisim_uzmani" },
                new Job{ JobName = "İç Mimar", JobCode = "ic_mimar" },
                new Job{ JobName = "Dış Ticaret Uzmanı", JobCode = "dis_ticaret_uzmani" },
                new Job{ JobName = "Kimya Mühendisi", JobCode = "kimya_muhendisi" },
                new Job{ JobName = "Mali Müşavir", JobCode = "mali_musavir" },
                new Job{ JobName = "E-Ticaret Uzmanı", JobCode = "eticaret_uzmani" }
            };

            await _context.Jobs.AddRangeAsync(jobs);
            await _context.SaveChangesAsync();
        }

        #endregion

        #region Roles

        UserType[] userTypes = new UserType[3]
    {
            UserType.SuperAdmin,
            UserType.Employer,
            UserType.Employee
    };

        for (int i =0; i<userTypes.Length;i++)
        {
            var insertRole = new ApplicationRole()
            {
                Id = userTypes[i].ToString(),
                Name = userTypes[i].ToString(),
            };
            if (!_roleManager.Roles.Any(r => r.Name == insertRole.Name))
            {
                await _roleManager.CreateAsync(insertRole);
            }
        }

        #endregion

        #region Super admin

        var adminUser = new ApplicationUser
        {
            UserName = "admin@bizebirilazim.com",
            Email = "admin@bizebirilazim.com",
            RefreshToken = Guid.NewGuid().ToString(),
            EmailConfirmed = true,
        };

        if (!_userManager.Users.Any(u => u.UserName == adminUser.UserName))
        {
            var isSuccess = await _userManager.CreateAsync(adminUser, "123456**Bbl");
            if (isSuccess.Succeeded)
            {
                await _userManager.AddToRolesAsync(adminUser, new[] {
                    UserType.SuperAdmin.ToString(),
                });
            }
        }

        #endregion

        #region Employer

        var employerUser = new ApplicationUser
        {
            UserName = "employer@bizebirilazim.com",
            Email = "employer@bizebirilazim.com",
            RefreshToken = Guid.NewGuid().ToString(),
            EmailConfirmed = true,
        };

        if (!_userManager.Users.Any(u => u.UserName == employerUser.UserName))
        {
            var isSuccess = await _userManager.CreateAsync(employerUser, "123456**Bbl");
            if (isSuccess.Succeeded)
            {

                await _userManager.AddToRolesAsync(employerUser, new[] {
                    UserType.Employer.ToString(),
                });

                var result= await _context.Employers.AddAsync(new Employer
                {
                    AspNetUserId = employerUser.Id,
                    CommercialTitle = "Yazılım",
                    FirstName = "Employer",
                    LastName = "Employer",
                    PhoneNumber = "8888888888",
                    Email = "employer@bizebirilazim.com"
                });

                await _context.SaveChangesAsync();
            }
        }

        #endregion

        #region Employee

        var EmployeeUser = new ApplicationUser
        {
            UserName = "employee@bizebirilazim.com",
            Email = "employee@bizebirilazim.com",
            RefreshToken = Guid.NewGuid().ToString(),
            EmailConfirmed = true,
        };

        if (!_userManager.Users.Any(u => u.UserName == EmployeeUser.UserName))
        {
            var isSuccess = await _userManager.CreateAsync(EmployeeUser, "123456**Bbl");
            if (isSuccess.Succeeded)
            {
                await _userManager.AddToRolesAsync(EmployeeUser, new[] {
                    UserType.Employee.ToString(),
                });

                var result = await _context.Employees.AddAsync(new Employee
                {
                    AspNetUserId = EmployeeUser.Id,
                    FirstName = "employee",
                    LastName = "employee",
                    PhoneNumber = "9999999999",
                    Email = "employee@bizebirilazim.com"
                });

                await _context.SaveChangesAsync();
            }
        }

        #endregion

        #region EmployerPricesRate

        if (!_context.EmployerPricesRate.Any())
        {
            await _context.EmployerPricesRate.AddAsync(new EmployerPriceRate
            {
                EmployerId = 1,
                CommissionFee = 3,
                LegalDeduction = 2
            });

            await _context.SaveChangesAsync();
        }

        #endregion


    }
}